const NAMES = [
  ["united states", "USA"],
  ["usa", "USA"],
  ["united kingdom", "UK"],
  ["britain", "UK"],
  ["england", "UK"],
  ["scotland", "UK"],
  ["wales", "UK"],
  ["new zealand", "New Zealand"],
  ["south africa", "South Africa"],
  ["czech republic", "Czechia"],
  ["czechia", "Czechia"],
  ["netherlands", "Netherlands"],
  ["deutschland", "Germany"],
  ["germany", "Germany"],
  ["portugal", "Portugal"],
  ["australia", "Australia"],
  ["argentina", "Argentina"],
  ["bulgaria", "Bulgaria"],
  ["croatia", "Croatia"],
  ["denmark", "Denmark"],
  ["france", "France"],
  ["greece", "Greece"],
  ["hungary", "Hungary"],
  ["ireland", "Ireland"],
  ["israel", "Israel"],
  ["italy", "Italy"],
  ["mexico", "Mexico"],
  ["norway", "Norway"],
  ["poland", "Poland"],
  ["romania", "Romania"],
  ["russia", "Russia"],
  ["serbia", "Serbia"],
  ["slovakia", "Slovakia"],
  ["slovenia", "Slovenia"],
  ["spain", "Spain"],
  ["sweden", "Sweden"],
  ["turkey", "Turkey"],
  ["ukraine", "Ukraine"],
  ["canada", "Canada"],
  ["brazil", "Brazil"],
  ["brasil", "Brazil"],
  ["cyprus", "Cyprus"],
  ["malaysia", "Malaysia"],
  ["india", "India"],
  ["pakistan", "Pakistan"],
  ["qatari", "Qatar"],
  ["qatar", "Qatar"],
  ["arabic", "Arabic"],
  ["afrique", "Africa"],
  ["africa", "Africa"],
  ["belgium", "Belgium"],
  ["austria", "Austria"],
  ["switzerland", "Switzerland"],
  ["finland", "Finland"],
  ["iceland", "Iceland"],
  ["japan", "Japan"],
  ["korea", "Korea"],
  ["china", "China"],
  ["hong kong", "Hong Kong"],
  ["singapore", "Singapore"],
  ["philippines", "Philippines"],
  ["thailand", "Thailand"],
  ["egypt", "Egypt"],
  ["morocco", "Morocco"],
  ["nigeria", "Nigeria"],
  ["chile", "Chile"],
  ["colombia", "Colombia"],
  ["peru", "Peru"],
  ["uruguay", "Uruguay"],
  ["ecuador", "Ecuador"],
  ["venezuela", "Venezuela"],
  ["albania", "Albania"],
  ["bosnia", "Bosnia"],
  ["macedonia", "North Macedonia"],
  ["montenegro", "Montenegro"],
  ["kosovo", "Kosovo"],
  ["latvia", "Latvia"],
  ["lithuania", "Lithuania"],
  ["estonia", "Estonia"],
];

const CODES = {
  us: "USA",
  usa: "USA",
  uk: "UK",
  gb: "UK",
  de: "Germany",
  cz: "Czechia",
  sk: "Slovakia",
  mx: "Mexico",
  nl: "Netherlands",
  ca: "Canada",
  nz: "New Zealand",
  au: "Australia",
  pt: "Portugal",
  br: "Brazil",
  fr: "France",
  es: "Spain",
  it: "Italy",
  pl: "Poland",
  gr: "Greece",
  tr: "Turkey",
  se: "Sweden",
  no: "Norway",
  dk: "Denmark",
  fi: "Finland",
  ie: "Ireland",
  be: "Belgium",
  at: "Austria",
  ch: "Switzerland",
  hu: "Hungary",
  ro: "Romania",
  bg: "Bulgaria",
  hr: "Croatia",
  rs: "Serbia",
  si: "Slovenia",
  ua: "Ukraine",
  ru: "Russia",
  il: "Israel",
  ae: "UAE",
  uae: "UAE",
  qa: "Qatar",
  sa: "Saudi Arabia",
  in: "India",
  pk: "Pakistan",
  my: "Malaysia",
  za: "South Africa",
  jp: "Japan",
  kr: "Korea",
  cn: "China",
  hk: "Hong Kong",
  sg: "Singapore",
  ar: "Argentina",
  cl: "Chile",
  co: "Colombia",
  pe: "Peru",
  uy: "Uruguay",
  cy: "Cyprus",
  al: "Albania",
  ba: "Bosnia",
  mk: "North Macedonia",
  me: "Montenegro",
  xk: "Kosovo",
  eg: "Egypt",
  ma: "Morocco",
  ng: "Nigeria",
  ph: "Philippines",
  th: "Thailand",
};

const BRANDS = [
  [/\bsky sports\b|\bsky atlantic\b|\bsky cinema\b|\bsky witness\b|\btnt sports\b|\bbt sport|\bbbc\b|\bitv\b|\bchannel 4\b|\beurosport .*uk\b/i, "UK"],
  [/\bespn\b|\bfox sports\b|\bnbc\b|\bcbs\b|\babc\b|\bcnn\b|\bmsnbc\b|\bhbo\b|\bshowtime\b|\bstarz\b|\busa network\b|\bparamount\+?|\bnfl network\b|\bmlb network\b|\bnba tv\b/i, "USA"],
  [/\btsn\b|\bsportsnet\b/i, "Canada"],
  [/\brai\b|\bmediaset\b|\bsky sport(s)? (ita|italia)/i, "Italy"],
  [/\bcanal\+|\bbein sports france|\btf1\b|\bfrance [2-5]\b/i, "France"],
  [/\bmovistar\b|\bdazn (es|spain)|\bcanal\+ (liga|deportes)/i, "Spain"],
  [/\bziggo\b|\bnpo\b/i, "Netherlands"],
  [/\bsupersport\b/i, "South Africa"],
  [/\bastro\b/i, "Malaysia"],
  [/\bcytavision\b/i, "Cyprus"],
  [/\barena sport\b/i, "Serbia"],
  [/\bpolsat\b|\bcanal\+ (poland|sport poland)|\btvp\b/i, "Poland"],
  [/\bsky (de|deutschland|sport austria)/i, "Germany"],
  [/\brtl\b|\bprosieben\b|\bsat\.1\b|\bzdf\b|\bard\b/i, "Germany"],
  [/\bfoxtel\b|\bkayo\b|\b9gem\b/i, "Australia"],
];

const FLAG = {
  us: "USA",
  gb: "UK",
  de: "Germany",
  fr: "France",
  it: "Italy",
  es: "Spain",
  pt: "Portugal",
  nl: "Netherlands",
  be: "Belgium",
  pl: "Poland",
  cz: "Czechia",
  sk: "Slovakia",
  hu: "Hungary",
  ro: "Romania",
  bg: "Bulgaria",
  hr: "Croatia",
  rs: "Serbia",
  gr: "Greece",
  tr: "Turkey",
  se: "Sweden",
  no: "Norway",
  dk: "Denmark",
  fi: "Finland",
  ie: "Ireland",
  at: "Austria",
  ch: "Switzerland",
  ca: "Canada",
  mx: "Mexico",
  br: "Brazil",
  ar: "Argentina",
  au: "Australia",
  nz: "New Zealand",
  za: "South Africa",
  in: "India",
  pk: "Pakistan",
  qa: "Qatar",
  ae: "UAE",
  il: "Israel",
  cy: "Cyprus",
  my: "Malaysia",
  jp: "Japan",
  kr: "Korea",
  cn: "China",
  ru: "Russia",
  ua: "Ukraine",
  eg: "Egypt",
};

function flagsToCountry(s) {
  const m = String(s).match(/[\u{1F1E6}-\u{1F1FF}]{2}/u);
  if (!m) return "";
  const a = m[0].codePointAt(0) - 0x1f1e6;
  const b = m[0].codePointAt(2) - 0x1f1e6;
  if (a < 0 || b < 0) return "";
  const code = String.fromCharCode(97 + a, 97 + b);
  return FLAG[code] || "";
}

export function countryFromName(name, fallback = "International") {
  const raw = String(name || "");
  const s = raw.split("—").pop() || raw;
  if (/18\+|adult/i.test(s)) return "18+";
  const flag = flagsToCountry(raw) || flagsToCountry(s);
  if (flag) return flag;
  const lower = s.toLowerCase().replace(/&/g, "&");
  const sorted = [...NAMES].sort((a, b) => b[0].length - a[0].length);
  for (const [needle, label] of sorted) {
    if (lower.includes(needle)) return label;
  }
  const tokens = lower.match(/[a-z]{2,}/g) || [];
  const last = tokens[tokens.length - 1];
  if (last && CODES[last]) return CODES[last];
  for (const t of tokens) {
    if (CODES[t] && t.length <= 3) return CODES[t];
  }
  for (const [re, label] of BRANDS) {
    if (re.test(s)) return label;
  }
  return fallback || "International";
}

export function withCountry(ch) {
  const group = countryFromName(ch.name || ch.group, ch.group || "International");
  return { ...ch, group };
}
