import path from "node:path";

function intEnv(name, fallback) {
  const value = Number(process.env[name]);
  return Number.isFinite(value) && value >= 0 ? value : fallback;
}
function boolEnv(name, fallback = false) {
  const value = process.env[name];
  if (value == null || value === "") return fallback;
  return /^(1|true|yes|on)$/i.test(value);
}
function cleanUrl(value, fallback = "") {
  return String(value || fallback).replace(/\/+$/, "");
}
function csvEnv(name, fallback = "") {
  return String(process.env[name] || fallback)
    .split(",")
    .map((x) => x.trim().toUpperCase())
    .filter(Boolean);
}

export const config = {
  port: intEnv("PORT", 8090),
  bindAddress: String(process.env.BIND_ADDRESS || "0.0.0.0"),
  internalPort: intEnv("INTERNAL_PORT", 8091),
  internalBindAddress: String(process.env.INTERNAL_BIND_ADDRESS || "0.0.0.0"),
  internalBaseUrl: cleanUrl(process.env.INTERNAL_BASE_URL, "http://justone-catalog:8091"),
  internalKey: String(process.env.INTERNAL_KEY || ""),
  dataDir: path.resolve(process.env.DATA_DIR || "./data"),
  adminKey: String(process.env.ADMIN_KEY || ""),

  providerRefreshMinutes: intEnv("PROVIDER_REFRESH_MINUTES", 24 * 60),
  dlhdRefreshMinutes: intEnv("DLHD_REFRESH_MINUTES", 8 * 60),
  providerCacheMaxAgeMinutes: intEnv("PROVIDER_CACHE_MAX_AGE_MINUTES", 24 * 60),

  fetchTimeoutMs: intEnv("FETCH_TIMEOUT_MS", 30000),
  playlistFetchTimeoutMs: intEnv("PLAYLIST_FETCH_TIMEOUT_MS", 30 * 60 * 1000),
  playlistMaxLineLength: intEnv("PLAYLIST_MAX_LINE_LENGTH", 4 * 1024 * 1024),
  qualityOrder: String(process.env.DEFAULT_QUALITY_ORDER || "HD,FHD,UHD,SD,UNKNOWN")
    .split(",").map((x) => x.trim().toUpperCase()).filter(Boolean),
  dlhd: {
    enabled: boolEnv("DLHD_FILTER_ENABLED", true),
    baseUrl: cleanUrl(process.env.DLHD_BASE_URL, "https://dlive.sx"),
    apiKey: String(process.env.DLHD_API_KEY || ""),
    include247: boolEnv("DLHD_INCLUDE_247", true),
    includeSchedule: boolEnv("DLHD_INCLUDE_SCHEDULE", true),
    includeUpcoming: boolEnv("DLHD_INCLUDE_UPCOMING", true),
    failClosed: boolEnv("DLHD_FAIL_CLOSED", true),
    staticCountries: csvEnv("DLHD_STATIC_COUNTRIES", "GB,PT,US"),
  },
  dispatcharr: {
    url: cleanUrl(process.env.DISPATCHARR_URL),
    apiKey: String(process.env.DISPATCHARR_API_KEY || ""),
    username: String(process.env.DISPATCHARR_USERNAME || ""),
    password: String(process.env.DISPATCHARR_PASSWORD || ""),
    applyEnabled: boolEnv("DISPATCHARR_APPLY_ENABLED", false),
    syncLogos: boolEnv("DISPATCHARR_SYNC_LOGOS", true),
  },
};

export function withInternalKey(url) {
  const u = new URL(url);
  // Event artwork is generated by a dedicated metadata-only listener on the
  // next internal port. It remains on media_net and is never host-published.
  if (u.pathname.startsWith("/artwork/") && Number(u.port || 80) === config.internalPort) {
    u.port = String(config.internalPort + 1);
  }
  if (config.internalKey) u.searchParams.set("key", config.internalKey);
  return u.toString();
}
