import path from "node:path";
import { installUpstreamXmltvCache } from "./upstream-xmltv-cache.js";

installUpstreamXmltvCache();

function intEnv(name, fallback) {
  const value = Number(process.env[name]);
  return Number.isFinite(value) && value >= 0 ? value : fallback;
}
function boolEnv(name, fallback = false) {
  const value = process.env[name];
  if (value == null || value === "") return fallback;
  return /^(1|true|yes|on)$/i.test(value);
}
function cleanUrl(value, fallback = "") {
  return String(value || fallback).replace(/\/+$/, "");
}
function csvEnv(name, fallback = "") {
  return String(process.env[name] || fallback)
    .split(",")
    .map((x) => x.trim().toUpperCase())
    .filter(Boolean);
}

export const config = {
  port: intEnv("PORT", 8090),
  bindAddress: String(process.env.BIND_ADDRESS || "0.0.0.0"),
  internalPort: intEnv("INTERNAL_PORT", 8091),
  internalBindAddress: String(process.env.INTERNAL_BIND_ADDRESS || "0.0.0.0"),
  internalBaseUrl: cleanUrl(process.env.INTERNAL_BASE_URL, "http://justone-catalog:8091"),
  internalKey: String(process.env.INTERNAL_KEY || ""),
  dataDir: path.resolve(process.env.DATA_DIR || "./data"),
  adminKey: String(process.env.ADMIN_KEY || ""),

  providerRefreshMinutes: intEnv("PROVIDER_REFRESH_MINUTES", 24 * 60),
  dlhdRefreshMinutes: intEnv("DLHD_REFRESH_MINUTES", 8 * 60),
  providerCacheMaxAgeMinutes: intEnv("PROVIDER_CACHE_MAX_AGE_MINUTES", 24 * 60),

  fetchTimeoutMs: intEnv("FETCH_TIMEOUT_MS", 30000),
  playlistFetchTimeoutMs: intEnv("PLAYLIST_FETCH_TIMEOUT_MS", 30 * 60 * 1000),
  playlistMaxLineLength: intEnv("PLAYLIST_MAX_LINE_LENGTH", 4 * 1024 * 1024),
  qualityOrder: String(process.env.DEFAULT_QUALITY_ORDER || "HD,FHD,UHD,SD,UNKNOWN")
    .split(",").map((x) => x.trim().toUpperCase()).filter(Boolean),

  streamProxy: {
    enabled: boolEnv("STREAM_PROXY_ENABLED", false),
    masterEnabled: boolEnv("STREAM_PROXY_MASTER_ENABLED", false),
    // Keep proxy bearer auth separate from the legacy internal-output key so
    // enabling the proxy cannot break an existing Dispatcharr rollback path.
    // INTERNAL_KEY remains a compatibility fallback for earlier deployments.
    key: String(process.env.STREAM_PROXY_KEY || process.env.INTERNAL_KEY || ""),
    startupTimeoutMs: intEnv("STREAM_STARTUP_TIMEOUT_MS", 8000),
    startupQueueTimeoutMs: intEnv("STREAM_STARTUP_QUEUE_TIMEOUT_MS", 1500),
    stallTimeoutMs: intEnv("STREAM_STALL_TIMEOUT_MS", 15000),
    relayGraceMs: intEnv("STREAM_RELAY_GRACE_MS", 8000),
    failoverWindowMs: intEnv("STREAM_FAILOVER_WINDOW_MS", 12000),
    failureCooldownMs: intEnv("STREAM_FAILURE_COOLDOWN_MS", 10000),
    notFoundCooldownMs: intEnv("STREAM_NOT_FOUND_COOLDOWN_MS", 300000),
    sourceFailureCooldownMs: intEnv("STREAM_SOURCE_FAILURE_COOLDOWN_MS", 60000),
    maxClientBufferBytes: intEnv("STREAM_MAX_CLIENT_BUFFER_BYTES", 8 * 1024 * 1024),
    startupBufferBytes: intEnv("STREAM_STARTUP_BUFFER_BYTES", 256 * 1024),
    replayBufferBytes: intEnv("STREAM_REPLAY_BUFFER_BYTES", 1024 * 1024),
    failoverKeepaliveMs: intEnv("STREAM_FAILOVER_KEEPALIVE_MS", 500),
    userAgent: String(process.env.STREAM_USER_AGENT || "VLC/3.0.20 LibVLC/3.0.20"),
  },
  dlhd: {
    enabled: boolEnv("DLHD_FILTER_ENABLED", true),
    baseUrl: cleanUrl(process.env.DLHD_BASE_URL, "https://dlive.sx"),
    apiKey: String(process.env.DLHD_API_KEY || ""),
    include247: boolEnv("DLHD_INCLUDE_247", true),
    includeSchedule: boolEnv("DLHD_INCLUDE_SCHEDULE", true),
    includeUpcoming: boolEnv("DLHD_INCLUDE_UPCOMING", true),
    failClosed: boolEnv("DLHD_FAIL_CLOSED", true),
    staticCountries: csvEnv("DLHD_STATIC_COUNTRIES", "ALL"),
  },
  dispatcharr: {
    url: cleanUrl(process.env.DISPATCHARR_URL),
    apiKey: String(process.env.DISPATCHARR_API_KEY || ""),
    username: String(process.env.DISPATCHARR_USERNAME || ""),
    password: String(process.env.DISPATCHARR_PASSWORD || ""),
    applyEnabled: boolEnv("DISPATCHARR_APPLY_ENABLED", false),
    syncLogos: boolEnv("DISPATCHARR_SYNC_LOGOS", true),
  },
};

export function withInternalKey(url) {
  const u = new URL(url);
  // Event artwork is generated by a dedicated metadata-only listener on the
  // next internal port. It remains on media_net and is never host-published.
  if (u.pathname.startsWith("/artwork/") && Number(u.port || 80) === config.internalPort) {
    u.port = String(config.internalPort + 1);
  }
  if (config.internalKey) u.searchParams.set("key", config.internalKey);
  return u.toString();
}


export function withStreamProxyKey(url) {
  const u = new URL(url);
  if (config.streamProxy.key) u.searchParams.set("key", config.streamProxy.key);
  return u.toString();
}
