export const ADMIN_HTML = String.raw`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>JustOne Catalog</title>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#f5f5f5;background:#101114}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1200px;margin:auto;padding:28px}h1{font-size:28px;margin:0 0 6px}h2{margin-top:0}.muted{color:#9ca3af}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:18px;margin-top:24px}.card{background:#181a1f;border:1px solid #2a2d34;border-radius:14px;padding:18px}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.grow{flex:1 1 360px}button,input,textarea{font:inherit}input,textarea{background:#101114;color:#fff;border:1px solid #343842;border-radius:8px;padding:10px 11px;width:100%}textarea{min-height:110px;resize:vertical}button{background:#f3f4f6;color:#111827;border:0;border-radius:8px;padding:9px 13px;font-weight:650;cursor:pointer}button.secondary{background:#2a2d34;color:#fff}button.danger{background:#4b2024;color:#fecaca}button:disabled{opacity:.5;cursor:not-allowed}.list{display:grid;gap:9px;margin-top:12px}.item{border:1px solid #2a2d34;border-radius:10px;padding:12px}.itemhead{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.item strong{display:block}.item small{display:block;color:#9ca3af;overflow-wrap:anywhere}.cols{display:grid;grid-template-columns:1fr 1fr;gap:9px}.status{display:flex;gap:16px;margin-top:18px;flex-wrap:wrap}.stat{background:#181a1f;border:1px solid #2a2d34;border-radius:12px;padding:12px 16px}.stat b{font-size:22px;display:block}.pill{display:inline-flex;align-items:center;border-radius:999px;padding:3px 8px;font-size:12px;font-weight:700;background:#272a31;color:#d1d5db}.pill.ok{background:#173923;color:#86efac}.pill.bad{background:#4b2024;color:#fecaca}.pill.off{background:#30323a;color:#9ca3af}.toolbar{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.notice{margin-top:14px;padding:10px 12px;border-radius:9px;background:#12141a;border:1px solid #2a2d34;color:#d1d5db}.notice.bad{border-color:#5f272d;color:#fecaca}.sep{height:1px;background:#2a2d34;margin:16px 0}details{border:1px solid #2a2d34;border-radius:9px;padding:10px 12px}summary{cursor:pointer;color:#d1d5db}pre{white-space:pre-wrap;max-height:420px;overflow:auto;background:#0b0c0f;padding:12px;border-radius:9px;color:#d1d5db}@media(max-width:600px){.cols{grid-template-columns:1fr}.wrap{padding:18px}}
</style>
</head>
<body><div class="wrap">
<div class="row" style="justify-content:space-between"><div><h1>JustOne Catalog</h1><div class="muted">DLHD-filtered IPTV catalog and Dispatcharr control plane.</div></div><button class="secondary" onclick="setKey()">Admin key</button></div>
<div class="status"><div class="stat"><b id="channels">—</b><span class="muted">channels</span></div><div class="stat"><b id="playlists">—</b><span class="muted">playlists</span></div><div class="stat"><b id="generated">—</b><span class="muted">last refresh</span></div></div>
<div id="notice" class="notice">Ready.</div>
<div class="row" style="margin-top:18px"><button onclick="refreshCatalog(true)">Refresh catalog</button><button class="secondary" onclick="previewDispatcharr()">Preview Dispatcharr</button><button class="secondary" onclick="loadAll()">Reload UI</button></div>
<div class="grid">
<section class="card" style="grid-column:1/-1">
<h2>Playlists</h2><div class="muted">For the normal case, just paste the M3U URL. JustOne assumes one connection and names the line automatically.</div>
<div class="row" style="margin-top:14px"><div class="grow"><input id="surl" type="url" placeholder="Paste M3U URL"></div><div style="flex:1 1 220px"><input id="sname" placeholder="Name (optional)"></div><button onclick="addSource()">Add playlist</button></div>
<div style="height:10px"></div>
<details><summary>Advanced settings (optional)</summary><div style="height:10px"></div><div class="cols"><input id="sprovider" placeholder="Provider name"><input id="saccount" placeholder="Account / line name"><input id="smax" type="number" value="1" min="1" placeholder="Max connections"><input id="spriority" type="number" value="10" placeholder="Priority"></div></details>
<div class="sep"></div>
<details><summary>Bulk add playlists</summary><div class="muted" style="margin:9px 0">Paste one URL per line, or use <b>Name | URL</b>.</div><textarea id="bulk" placeholder="https://provider-a.example/list.m3u\nProvider B line 1 | https://provider-b.example/get.php?...\nProvider B line 2 | https://provider-b.example/get.php?..."></textarea><div class="toolbar"><button onclick="bulkAdd()">Add all</button></div></details>
<div class="sep"></div>
<div id="sources" class="list"></div>
</section>
<section class="card"><h2>EPG guides</h2><div class="muted">Optional XMLTV sources. Lower priority number wins.</div><div id="guides" class="list"></div><h3>Add guide</h3><div class="cols"><input id="gname" placeholder="UK Guide"><input id="gpriority" type="number" value="10"></div><div style="height:9px"></div><input id="gurl" type="url" placeholder="https://…/guide.xml"><div style="height:9px"></div><button onclick="addGuide()">Add guide</button></section>
<section class="card"><h2>Dispatcharr preview</h2><div id="preview" class="muted">Run preview to see planned channel creates/updates.</div></section>
</div></div>
<script>
const keyName='justone_admin_key';
let sourceRows=[];let outputRows=[];let sourceStatus=[];
function key(){let k=sessionStorage.getItem(keyName);if(!k){k=prompt('JustOne ADMIN_KEY');if(k)sessionStorage.setItem(keyName,k)}return k||''}
function setKey(){const k=prompt('JustOne ADMIN_KEY',sessionStorage.getItem(keyName)||'');if(k!==null)sessionStorage.setItem(keyName,k)}
async function api(path,opts={}){const headers={...(opts.headers||{}),'X-Admin-Key':key()};if(opts.body&&!headers['Content-Type'])headers['Content-Type']='application/json';const r=await fetch(path,{...opts,headers});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||('HTTP '+r.status));return data}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function say(message,bad=false){notice.textContent=message;notice.className='notice'+(bad?' bad':'')}
function host(v){try{return new URL(v).hostname}catch{return 'playlist'}}
function statusFor(id){return sourceStatus.find(x=>x.id===id)||null}
function outputFor(id){return outputRows.find(x=>x.id===id)?.url||''}
async function loadAll(){try{const [snap,sources,guides,outputs]=await Promise.all([api('/api/catalog'),api('/api/sources'),api('/api/guides'),api('/api/internal-outputs')]);sourceRows=sources;outputRows=outputs.sources||[];sourceStatus=snap.sourceStatus||[];channels.textContent=snap.channels?.length??0;playlists.textContent=sources.length;generated.textContent=snap.generatedAt?new Date(snap.generatedAt).toLocaleString():'never';renderSources(sources);renderGuides(guides);say('Ready. '+sources.length+' playlist'+(sources.length===1?'':'s')+' configured.')}catch(e){say(e.message,true)}}
function renderSources(rows){sources.innerHTML=rows.map(x=>{const st=statusFor(x.id);const enabled=x.enabled!==false;const cls=!enabled?'off':st?.ok?'ok':st?'bad':'';const label=!enabled?'Disabled':st?.ok?((st.rows??0)+' rows'):st?('Error'):'Not refreshed';const out=outputFor(x.id);return '<div class="item"><div class="itemhead"><div><strong>'+esc(x.name)+'</strong><small>'+esc(x.provider||'')+' / '+esc(x.account||'')+' · max '+esc(x.maxStreams||1)+' connection'+((x.maxStreams||1)===1?'':'s')+'</small><small>'+esc(host(x.url))+'</small></div><span class="pill '+cls+'">'+esc(label)+'</span></div>'+(st&&!st.ok?'<small class="bad">'+esc(st.error||'Refresh failed')+'</small>':'')+'<div class="toolbar"><button class="secondary" onclick="toggleSource(\''+esc(x.id)+'\','+(enabled?'false':'true')+')">'+(enabled?'Disable':'Enable')+'</button><button class="secondary" onclick="editSource(\''+esc(x.id)+'\')">Edit</button>'+(out?'<button class="secondary" onclick="copyText(\''+esc(out)+'\')">Copy internal M3U</button>':'')+'<button class="danger" onclick="removeSource(\''+esc(x.id)+'\',\''+esc(x.name)+'\')">Remove</button></div></div>'}).join('')||'<div class="muted">No playlists yet. Paste an M3U URL above to add the first one.</div>'}
function renderGuides(rows){guides.innerHTML=rows.map(x=>'<div class="item"><strong>'+esc(x.name)+'</strong><small>priority '+esc(x.priority||100)+'</small><small>'+esc(host(x.url))+'</small><div class="toolbar"><button class="danger" onclick="delGuide(\''+esc(x.id)+'\')">Remove</button></div></div>').join('')||'<div class="muted">No XMLTV guides configured.</div>'}
async function refreshCatalog(showMessage=false){try{say('Refreshing catalog…');const data=await api('/api/refresh',{method:'POST'});channels.textContent=data.channels.length;generated.textContent=new Date(data.generatedAt).toLocaleString();if(showMessage)say('Refresh complete: '+data.channels.length+' channels.');await loadAll();return data}catch(e){say(e.message,true);throw e}}
async function refreshAfterChange(action){try{say(action+' Saved. Refreshing catalog…');await refreshCatalog(false);say(action+' Done.')}catch(e){}}
async function addSource(){if(!surl.value.trim()){say('Paste an M3U URL first.',true);return}try{say('Adding playlist…');const payload={url:surl.value.trim()};if(sname.value.trim())payload.name=sname.value.trim();if(sprovider.value.trim())payload.provider=sprovider.value.trim();if(saccount.value.trim())payload.account=saccount.value.trim();payload.maxStreams=Number(smax.value||1);payload.priority=Number(spriority.value||10);await api('/api/sources',{method:'POST',body:JSON.stringify(payload)});surl.value=sname.value=sprovider.value=saccount.value='';smax.value='1';spriority.value='10';await refreshAfterChange('Playlist added.')}catch(e){say(e.message,true)}}
async function bulkAdd(){const text=bulk.value.trim();if(!text){say('Paste at least one playlist URL.',true);return}try{say('Adding playlists…');const result=await api('/api/sources/bulk',{method:'POST',body:JSON.stringify({text})});if(result.counts.added)bulk.value='';await refreshAfterChange(result.counts.added+' playlist'+(result.counts.added===1?'':'s')+' added'+(result.counts.skipped?' ('+result.counts.skipped+' skipped)':'')+'.')}catch(e){say(e.message,true)}}
async function toggleSource(id,enabled){try{await api('/api/sources/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({enabled})});await refreshAfterChange(enabled?'Playlist enabled.':'Playlist disabled.')}catch(e){say(e.message,true)}}
async function editSource(id){const row=sourceRows.find(x=>x.id===id);if(!row)return;const name=prompt('Playlist name',row.name||'');if(name===null)return;const url=prompt('M3U URL',row.url||'');if(url===null)return;const max=prompt('Max connections',String(row.maxStreams||1));if(max===null)return;try{await api('/api/sources/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({name:name.trim(),url:url.trim(),maxStreams:Number(max||1)})});await refreshAfterChange('Playlist updated.')}catch(e){say(e.message,true)}}
async function removeSource(id,name){if(!confirm('Remove '+name+'?'))return;try{await api('/api/sources/'+encodeURIComponent(id),{method:'DELETE'});await refreshAfterChange('Playlist removed.')}catch(e){say(e.message,true)}}
async function copyText(value){try{await navigator.clipboard.writeText(value);say('Internal M3U URL copied.')}catch{prompt('Copy internal M3U URL',value)}}
async function addGuide(){try{await api('/api/guides',{method:'POST',body:JSON.stringify({name:gname.value,priority:Number(gpriority.value||10),url:gurl.value,enabled:true})});gname.value=gurl.value='';await refreshAfterChange('Guide added.')}catch(e){say(e.message,true)}}
async function delGuide(id){if(!confirm('Remove this guide?'))return;try{await api('/api/guides/'+encodeURIComponent(id),{method:'DELETE'});await refreshAfterChange('Guide removed.')}catch(e){say(e.message,true)}}
async function previewDispatcharr(){preview.textContent='Loading…';try{const data=await api('/api/dispatcharr/preview');preview.innerHTML='<div class="row">'+Object.entries(data.counts||{}).map(([k,v])=>'<span><b>'+esc(v)+'</b> '+esc(k)+'</span>').join('')+'</div><pre>'+esc(JSON.stringify(data.actions,null,2))+'</pre>'}catch(e){preview.innerHTML='<span class="bad">'+esc(e.message)+'</span>'}}
loadAll();
</script></body></html>`;
