export const ADMIN_HTML = String.raw`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>JustOne Catalog</title>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#f5f5f5;background:#101114}body{margin:0}.wrap{max-width:1200px;margin:auto;padding:28px}h1{font-size:28px;margin:0 0 6px}.muted{color:#9ca3af}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:18px;margin-top:24px}.card{background:#181a1f;border:1px solid #2a2d34;border-radius:14px;padding:18px}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}button,input{font:inherit}input{background:#101114;color:#fff;border:1px solid #343842;border-radius:8px;padding:9px 10px;box-sizing:border-box}input[type=text],input[type=url],input[type=number],input[type=password]{width:100%}button{background:#f3f4f6;color:#111827;border:0;border-radius:8px;padding:9px 13px;font-weight:650;cursor:pointer}button.secondary{background:#2a2d34;color:#fff}button.danger{background:#4b2024;color:#fecaca}.list{display:grid;gap:9px;margin-top:12px}.item{border:1px solid #2a2d34;border-radius:9px;padding:11px}.item strong{display:block}.item small{display:block;color:#9ca3af;overflow-wrap:anywhere}.cols{display:grid;grid-template-columns:1fr 1fr;gap:9px}.status{display:flex;gap:16px;margin-top:18px}.stat{background:#181a1f;border:1px solid #2a2d34;border-radius:12px;padding:12px 16px}.stat b{font-size:22px;display:block}pre{white-space:pre-wrap;max-height:420px;overflow:auto;background:#0b0c0f;padding:12px;border-radius:9px;color:#d1d5db}.ok{color:#86efac}.bad{color:#fca5a5}@media(max-width:600px){.cols{grid-template-columns:1fr}.wrap{padding:18px}}
</style>
</head>
<body><div class="wrap">
<div class="row" style="justify-content:space-between"><div><h1>JustOne Catalog</h1><div class="muted">Metadata and Dispatcharr control plane. No video proxy. No FFmpeg.</div></div><button class="secondary" onclick="setKey()">Admin key</button></div>
<div class="status"><div class="stat"><b id="channels">—</b><span class="muted">channels</span></div><div class="stat"><b id="generated">—</b><span class="muted">last refresh</span></div></div>
<div class="row" style="margin-top:18px"><button onclick="refreshCatalog()">Refresh catalog</button><button class="secondary" onclick="previewDispatcharr()">Preview Dispatcharr</button><button class="secondary" onclick="loadAll()">Reload UI</button></div>
<div class="grid">
<section class="card"><h2>Sources</h2><div class="muted">One entry per provider credential/line.</div><div id="sources" class="list"></div><h3>Add source</h3><div class="cols"><input id="sname" placeholder="Provider A - Line 1"><input id="sprovider" placeholder="Provider A"><input id="saccount" placeholder="Line 1"><input id="smax" type="number" value="1" min="1"></div><div style="height:9px"></div><input id="surl" type="url" placeholder="https://…/playlist.m3u"><div style="height:9px"></div><button onclick="addSource()">Add source</button></section>
<section class="card"><h2>EPG guides</h2><div class="muted">Higher-priority guides should use lower priority numbers.</div><div id="guides" class="list"></div><h3>Add guide</h3><div class="cols"><input id="gname" placeholder="UK Guide"><input id="gpriority" type="number" value="10"></div><div style="height:9px"></div><input id="gurl" type="url" placeholder="https://…/guide.xml"><div style="height:9px"></div><button onclick="addGuide()">Add guide</button></section>
<section class="card" style="grid-column:1/-1"><h2>Dispatcharr preview</h2><div id="preview" class="muted">Run preview to see planned channel creates/updates.</div></section>
</div></div>
<script>
const keyName='justone_admin_key';
function key(){let k=sessionStorage.getItem(keyName);if(!k){k=prompt('JustOne ADMIN_KEY');if(k)sessionStorage.setItem(keyName,k)}return k||''}
function setKey(){const k=prompt('JustOne ADMIN_KEY',sessionStorage.getItem(keyName)||'');if(k!==null)sessionStorage.setItem(keyName,k)}
async function api(path,opts={}){const headers={...(opts.headers||{}),'X-Admin-Key':key()};if(opts.body&&!headers['Content-Type'])headers['Content-Type']='application/json';const r=await fetch(path,{...opts,headers});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||('HTTP '+r.status));return data}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function loadAll(){try{const [snap,sources,guides]=await Promise.all([api('/api/catalog'),api('/api/sources'),api('/api/guides')]);channels.textContent=snap.channels?.length??0;generated.textContent=snap.generatedAt?new Date(snap.generatedAt).toLocaleString():'never';renderSources(sources);renderGuides(guides)}catch(e){alert(e.message)}}
function renderSources(rows){sources.innerHTML=rows.map(x=>'<div class="item"><strong>'+esc(x.name)+'</strong><small>'+esc(x.provider||'')+' / '+esc(x.account||'')+' · max '+esc(x.maxStreams||1)+'</small><small>'+esc(x.url)+'</small><div style="height:8px"></div><button class="danger" onclick="del(\'sources\',\''+esc(x.id)+'\')">Delete</button></div>').join('')||'<div class="muted">No sources yet.</div>'}
function renderGuides(rows){guides.innerHTML=rows.map(x=>'<div class="item"><strong>'+esc(x.name)+'</strong><small>priority '+esc(x.priority||100)+'</small><small>'+esc(x.url)+'</small><div style="height:8px"></div><button class="danger" onclick="del(\'guides\',\''+esc(x.id)+'\')">Delete</button></div>').join('')||'<div class="muted">No guides yet.</div>'}
async function addSource(){try{await api('/api/sources',{method:'POST',body:JSON.stringify({name:sname.value,provider:sprovider.value,account:saccount.value,maxStreams:Number(smax.value||1),priority:10,url:surl.value,enabled:true})});sname.value=sprovider.value=saccount.value=surl.value='';await loadAll()}catch(e){alert(e.message)}}
async function addGuide(){try{await api('/api/guides',{method:'POST',body:JSON.stringify({name:gname.value,priority:Number(gpriority.value||10),url:gurl.value,enabled:true})});gname.value=gurl.value='';await loadAll()}catch(e){alert(e.message)}}
async function del(type,id){if(!confirm('Delete this '+type.slice(0,-1)+'?'))return;try{await api('/api/'+type+'/'+encodeURIComponent(id),{method:'DELETE'});await loadAll()}catch(e){alert(e.message)}}
async function refreshCatalog(){try{const data=await api('/api/refresh',{method:'POST'});channels.textContent=data.channels.length;generated.textContent=new Date(data.generatedAt).toLocaleString();alert('Refresh complete: '+data.channels.length+' channels')}catch(e){alert(e.message)}}
async function previewDispatcharr(){preview.textContent='Loading…';try{const data=await api('/api/dispatcharr/preview');preview.innerHTML='<div class="row">'+Object.entries(data.counts||{}).map(([k,v])=>'<span><b>'+esc(v)+'</b> '+esc(k)+'</span>').join('')+'</div><pre>'+esc(JSON.stringify(data.actions,null,2))+'</pre>'}catch(e){preview.innerHTML='<span class="bad">'+esc(e.message)+'</span>'}}
loadAll();
</script></body></html>`;
